##The attached R script filw contains all of the R code needed to reproduce the results (numbers, plots, etc.) in the report. 
##Following Steps are taken. 

##Code for reading in the dataset and/or processing the data
##Histogram of the total number of steps taken each day
##Mean and median number of steps taken each day
##Time series plot of the average number of steps taken
##The 5-minute interval that, on average, contains the maximum number of steps
##Code to describe and show a strategy for imputing missing data
##Histogram of the total number of steps taken each day after missing values are imputed
##Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends

##Now the R Script

##Loading and preprocessing the data
echo = TRUE
setwd("~/Data Science/Course 5 - Reproducible Research/Week 2/Week 2 Assignment")
acti_data <- read.csv("activity.csv")
summary(acti_data)
head(acti_data)

## The missing values in the dataset are ignored.
## Calculate the total number of steps taken per day
steps <- aggregate(acti_data$steps, by = list(Date = acti_data$date), FUN = sum)
library(ggplot2)
names(steps)[names(steps) == "x"] <- "Total"
temp <- as.Date(steps$Date, "%Y-%m-%d")
steps$Date <- format(temp, format = "%m-%d")
head(steps)

## Make a histogram of the total number of steps taken each day.
hist1 <- ggplot(data = na.omit(steps), aes(Total)) + 
  geom_histogram(binwidth = 1500, colour = "white") +
  xlab("Total Number of Steps Taken Each Day") +
  ylab("Count") +
  ggtitle("Histogram of the Total Number of Steps Taken Each Day")
print(hist1)

##Calculate and report the mean and median of the total number of steps taken per day
mean(na.omit(steps$Total))
median(na.omit(steps$Total))

##What is the average daily activity pattern
## Make a time series plot (i.e. ???????????????? = "????") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis) type = "l" means the plot is line 
## graph.
five_min_steps <- aggregate(steps ~ interval, data = acti_data, FUN =mean)
TimeSeries1 <- ggplot(data = five_min_steps, aes(x = interval, y = steps)) + 
  geom_line() +
  xlab("Time Intervals (5 Minutes is an unit)") + 
  ylab("Total Number of Steps") +
  ggtitle("Average Number of Steps Taken of the 5-Minute Interval")
print(TimeSeries1)

## Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
head(five_min_steps)
five_min_steps[which(five_min_steps$steps == max(five_min_steps$steps)),]

##Imputing missing values
## 1. Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
sapply(X = acti_data, FUN = function(x) sum(is.na(x)))

## 2. Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc. I will use the mean for that 5 -minute interval to replace all the missing values in the dataset. At the end, I will check if all the NAs have been replaced.
library(dplyr)
## 
## Attaching package: 'dplyr'
## The following objects are masked from 'package:stats':
## 
##     filter, lag
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
replace_with_mean <- function(num) replace(num, is.na(num), mean(num, na.rm = TRUE))
meanday <- (acti_data %>% group_by(interval) %>% mutate(steps = replace_with_mean(steps)))
head(meanday)
sum(is.na(meanday))

## 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.
new_dataset <- as.data.frame(meanday)
head(new_dataset)
summary(new_dataset)

## 4. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps? We make a histogram of the total number of steps taken each day first by using the new version dataset
new_steps <- aggregate(new_dataset$steps, by = list(new_dataset$date), FUN = sum)
names(new_steps)[names(new_steps) == "x"] <- "Total"
names(new_steps)[names(new_steps) == "Group.1"] <- "Date"
hist2 <- ggplot(data = new_steps, aes(Total)) + 
  geom_histogram(binwidth = 1500, colour = "white") +
  xlab("Total Number of Steps Taken Each Day") +
  ylab("Count") +
  ggtitle("Histogram of the Total Number of Steps Taken Each Day with New Version Dataset")
print(hist2)

##Now, we compare two plots.
library(grid)
library(gridExtra)
## 
## Attaching package: 'gridExtra'
## The following object is masked from 'package:dplyr':
## 
##     combine
grid.arrange(hist1, hist2, ncol = 2)

##Compare the mean and median:
mean(na.omit(steps$Total))
median(na.omit(steps$Total))
mean(new_steps$Total)
median(new_steps$Total)
##From the comparison, we can see that the highest count of the new version data is larger than the one we have with NAs. The means of each dataset are same. The medians of each dataset are slightly different.

##Are there differences in activity patterns between weekdays and weekends?
##Use the dataset with the filled-in missing values which is called new_steps dataset.
## 1.  Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
new_dataset$WeekendOrWeekday <- ifelse(weekdays(as.Date(new_dataset$date)) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), "Weekday", "Weekend")
head(new_dataset)
## 2. Make a panel plot containing a time series plot (i.e. ???????????????? = "????") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.
new_dataset <- (new_dataset %>% group_by(interval, WeekendOrWeekday) %>% summarise(Mean = mean(steps)))
ggplot(new_dataset, mapping = aes(x = interval, y = Mean)) + geom_line() +
  facet_grid(WeekendOrWeekday ~.) + xlab("Interval") + ylab("Mean of Steps") +
  ggtitle("Comparison of Average Number of Steps in Each Interval")
##There are differences in activity patterns between weekdays and weekends. Compared with weekdays, during weekends, people tend to get up late and stay up late. On weekends, people tend to be more active, since their steps are not stable caused of not working.

